# Generated by Django 5.1 on 2024-08-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['post_datetime']},
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='comment_datetime',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='post_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='username',
            field=models.CharField(default='random123', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(),
        ),
    ]
