# Generated by Django 5.1 on 2024-08-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcomment_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='post_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
